_target_: pipelines.rl_agent_policy.train.a2c.A2CTrainer

approach:
  _target_: pipelines.rl_agent_policy.train.a2c.A2CConfig
  batch_size: 128
  discount_factor: 0.9999
  learning_rate: 0.0001
  eps_start: 0.9
  eps_end: 0.05
  eps_decay_steps: 200
  entropy_c: 0.0001
  memory_capacity: 1000
  n_steps: null
  n_episodes: 100000
  validate_every_episodes: 500
  checkpoint_every_episodes: 1000
  resume_path: null
  gradient_accumulation_steps: 2  # Number of steps to accumulate gradients before updating
  