_target_: pipelines.a2c_agent.train.a2c.A2CTrainer

approach:
  _target_: pipelines.a2c_agent.train.a2c.A2CConfig
  batch_size: 128
  discount_factor: 0.9999
  learning_rate: 0.0001
  eps_start: 0.9
  eps_end: 0.05
  eps_decay_steps: 200
  entropy_c: 0.0001
  memory_capacity: 1000
  n_steps: null
  n_episodes: 1
  output_dir: runs/a2c
  checkpoint_every_steps: 1000
  resume_path: null
