_target_: pipelines.a2c_agent.train.ppo.PPOTrainer

approach:
  _target_: pipelines.a2c_agent.train.ppo.PPOConfig
  batch_size: 2048
  mini_batch_size: 64
  epochs: 10
  gamma: 0.99
  lam: 0.95
  clip_range: 0.2
  learning_rate: 0.0003
  ent_coef: 0.0
  vf_coef: 0.5
  max_grad_norm: 0.5
  n_steps: null
  n_episodes: 1
  output_dir: runs/ppo
  checkpoint_every_steps: 1000
  resume_path: null
