seed: 42

output_dir: pipelines/z_score_mean_reversion/outputs

log_level: INFO


data:
  currency: "BTC"
  main_currency: "USDT"
  exchange: "Binance"
  time_frame: "1d"
  start_date: null
  end_date: null

environment:
  exchange: "simulator"
  window_size: 30
  max_episode_length: null
  initial_cash: 10000.0
  initial_amount: 0.0
  renderer_formats:
    - png
    - html
  renderers:
    - matplot
    - sharpe-matplot
    - pnl-extrema-matplot
    - roi-matplot
    - drawdown-matplot
    - pnl-matplot
    - calmar-plotly
    - hitratio-plotly
    - turnover-plotly

strategy:
  window: 60
  entry_threshold: 1.5
  sensitivity: 0.5
  max_weight: 1.0
  ewma_lambda: 0.94
  target_volatility: 0.02
  volatility_floor: 1.0e-06
  fee_rate: 0.001
  slippage_rate: 0.0005
  epsilon: 0.1

simulation:
  tolerance: 1.0e-06
  include_discrete_signal: true
  warmup_steps: 60
